# Generated by Django 5.2.8 on 2025-11-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('TTLOCK', 'TTLock'), ('IGLOO', 'igloohome'), ('AQARA', 'Aqara')], max_length=16)),
                ('external_id', models.CharField(help_text='Lock ID at vendor', max_length=128)),
                ('name', models.CharField(max_length=120)),
                ('room_id', models.CharField(max_length=64)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('supports_pin', models.BooleanField(default=True)),
                ('supports_cloud', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='wallet', max_length=16)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('wallet_object_id', models.CharField(blank=True, max_length=128, null=True)),
                ('wallet_jwt', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.smartlock')),
            ],
        ),
    ]
