# Generated by Django 5.2.8 on 2025-11-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user_alter_booking_guest_name_and_more'),
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspass',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='type',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='wallet_jwt',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='wallet_object_id',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='supports_cloud',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='supports_pin',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='vendor',
        ),
        migrations.AddField(
            model_name='smartlock',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='lock_api_id',
            field=models.CharField(default='TEMP_LOCK_ID', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smartlock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
