# Generated by Django 5.2.8 on 2025-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_rename_active_accesspass_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartlock',
            name='lock_api_id',
        ),
        migrations.AddField(
            model_name='accesspass',
            name='wallet_jwt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='wallet_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='external_id',
            field=models.CharField(blank=True, help_text='Lock ID from vendor API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='vendor',
            field=models.CharField(choices=[('TTLOCK', 'TTLock'), ('AQARA', 'Aqara'), ('IGLOO', 'Igloohome')], default='TTLOCK', max_length=20),
        ),
    ]
