# Generated by Django 5.0.6 on 2025-11-13 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_remove_smartlock_lock_api_id_accesspass_wallet_jwt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspass',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='code',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='smartlock',
            name='vendor',
        ),
        migrations.AddField(
            model_name='accesspass',
            name='smartlock_key_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='smartlock_pin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='wallet_save_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartlock',
            name='lock_id',
            field=models.CharField(default='DEFAULT_LOCK', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartlock',
            name='provider',
            field=models.CharField(default='igloohome', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='wallet_object_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smartlock',
            name='room_id',
            field=models.CharField(default='UNASSIGNED', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
