# Generated by Django 5.0.6 on 2025-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0004_rename_is_active_accesspass_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartlock',
            name='provider',
            field=models.CharField(default='ttlock', max_length=50),
        ),
    ]
