# Generated by Django 5.0.6 on 2025-11-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0005_alter_smartlock_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartLock',
            new_name='Lock',
        ),
    ]
