# Generated by Django 5.0.6 on 2025-11-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user_alter_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='smartlock_code',
            field=models.CharField(blank=True, help_text='PIN / key code from Igloohome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='smartlock_key_id',
            field=models.CharField(blank=True, help_text='Key ID from Igloohome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wallet_object_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wallet_save_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
