# Generated by Django 5.0.6 on 2025-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_smartlock_code_booking_smartlock_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='smartlock_code',
            field=models.CharField(blank=True, help_text='PIN / key code from TTLock', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='smartlock_key_id',
            field=models.CharField(blank=True, help_text='Key ID from TTLock', max_length=100, null=True),
        ),
    ]
