# Generated by Django 5.0.6 on 2025-11-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_smartlock_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='smartlock_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='smartlock_key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
